routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\AdminProfileController;
use App\Http\Controllers\CedulaRequestController;
use App\Http\Controllers\UserProfileController;
use App\Http\Controllers\SportEquipmentController;
use App\Http\Controllers\BarangayEquipmentController;
use App\Http\Controllers\AdminUserManagementController;
use App\Http\Controllers\AnnouncementController;
use App\Http\Controllers\AdminContactController;
use App\Http\Controllers\UserSportsEquipmentController;
use App\Http\Controllers\UserBrgyEquipmentController;
use App\Http\Controllers\AdminRequestSport;
use App\Http\Controllers\AdminRequestBrgy;
use App\Http\Controllers\CourtRequestController;
use App\Http\Controllers\SystemController;
use App\Http\Controllers\BrgyClearanceController;
use App\Http\Controllers\BrgyIndigencyController;
use App\Http\Controllers\UserBrgyClearanceController;
use App\Http\Controllers\UserBrgyIndigencyController;
use App\Http\Controllers\AdminGymController;
use App\Http\Controllers\ReportsController;
use App\Http\Controllers\VerifyAccountController;
use App\Http\Controllers\AdminVerifyController;


// Login
Route::get('/', [AuthController::class, 'index'])->name('login');
Route::post('/login', [AuthController::class, 'check_login'])->name('auth.check');
Route::get('/logout', [AuthController::class, 'logoutUser'])->name('auth.logout');
Route::get('/registration', [AuthController::class, 'registration'])->name('auth.registration');
Route::post('/registration/add', [AuthController::class, 'registrationAdd'])->name('auth.registration.add');
Route::get('/forget_pass', [AuthController::class, 'forgetPass'])->name('auth.forget_pass');
Route::post('/forget_pass/save', [AuthController::class, 'forgetPassSave'])->name('auth.forget_pass_save');
Route::get('/change/password/{id?}', [AuthController::class, 'changePass'])->name('auth.change_password');
Route::post('/change/password/save/{id?}', [AuthController::class, 'changePassSave'])->name('auth.change_password_save');
Route::post('/reset/password/save/{id?}', [AuthController::class, 'resetPassSave'])->name('auth.reset_password_save');


// admin modules
Route::group(['middleware' => ['auth', 'AuthAdmin']], function(){
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function(){

// admin Dashboard
Route::get('/dashboard', [DashboardController::class, 'index'])->name('index');

//admin Verify
Route::get('admin-verify/', [AdminVerifyController::class, 'index'])->name('verify.index');
Route::get('admin-verify/list', [AdminVerifyController::class, 'list'])->name('verify.list');
Route::get('admin-verify/find/{id?}', [AdminVerifyController::class, 'find'])->name('verify.find');
Route::post('admin-verify/approve/{id?}', [AdminVerifyController::class, 'approve'])->name('verify.approve');
Route::post('admin-verify/disapprove/{id?}', [AdminVerifyController::class, 'disapprove'])->name('verify.disapprove');



//admin profile
Route::get('profile', [AdminProfileController::class, 'index'])->name('profile.index');
Route::post('profile/edit', [AdminProfileController::class, 'edit'])->name('profile.edit');
Route::get('profile/find/{id?}', [AdminProfileController::class, 'find'])->name('profile.find');
Route::get('profile/change-password', [AdminProfileController::class, 'changePassword'])->name('profile.change.password');
Route::post('profile/upload', [AdminProfileController::class, 'upload'])->name('profile.upload');

//AdminUserInformationController
Route::get('UserInformation', [AdminUserInformationController::class, 'index'])->name('UserInformation.index');
Route::get('UserInformation/list', [AdminUserInformationController::class, 'list'])->name('UserInformation.list');

//sports_equipment
Route::get('sports/equipments', [SportEquipmentController::class, 'index'])->name('sports.index');
Route::get('sports/store', [SportEquipmentController::class, 'store'])->name('sports.store');
Route::get('sports/list', [SportEquipmentController::class, 'list'])->name('sports.list');
Route::get('sports/find/{id?}', [SportEquipmentController::class, 'find'])->name('sports.find');
Route::post('sports/destroy/{id?}', [SportEquipmentController::class, 'destroy'])->name('sports.destroy');
Route::get('sports/select', [SportEquipmentController::class, 'select'])->name('sports.select');
Route::get('sports/qnty/{id?}', [SportEquipmentController::class, 'qnty'])->name('sports.qnty');
Route::post('sports/stock-in', [SportEquipmentController::class, 'stockIn'])->name('sports.stockIn');
Route::post('sports/stock-out', [SportEquipmentController::class, 'stockOut'])->name('sports.stockOut');

//barangay_equipment
Route::get('barangay/equipments', [BarangayEquipmentController::class, 'index'])->name('barangay.index');
Route::get('barangay/store', [BarangayEquipmentController::class, 'store'])->name('barangay.store');
Route::get('barangay/list', [BarangayEquipmentController::class, 'list'])->name('barangay.list');
Route::get('barangay/find/{id?}', [BarangayEquipmentController::class, 'find'])->name('barangay.find');
Route::post('barangay/destroy/{id?}', [BarangayEquipmentController::class, 'destroy'])->name('barangay.destroy');
Route::get('barangay/select', [BarangayEquipmentController::class, 'select'])->name('barangay.select');
Route::get('barangay/qnty/{id?}', [BarangayEquipmentController::class, 'qnty'])->name('barangay.qnty');
Route::post('barangay/stock-in', [BarangayEquipmentController::class, 'stockIn'])->name('barangay.stockIn');
Route::post('barangay/stock-out', [BarangayEquipmentController::class, 'stockOut'])->name('barangay.stockOut');

//user_management
Route::get('user-management/', [AdminUserManagementController::class, 'index'])->name('users.index');
Route::get('user-management/store', [AdminUserManagementController::class, 'store'])->name('users.store');
Route::get('user-management/list', [AdminUserManagementController::class, 'list'])->name('users.list');
Route::get('user-management/find/{id?}', [AdminUserManagementController::class, 'find'])->name('users.find');
Route::delete('user-management/destroy/{id?}', [AdminUserManagementController::class, 'destroy'])->name('users.destroy');

//announcement
Route::get('announcement/', [AnnouncementController::class, 'index'])->name('announcement.index');
Route::post('announcement/store', [AnnouncementController::class, 'store'])->name('announcement.store');
Route::get('announcement/list', [AnnouncementController::class, 'list'])->name('announcement.list');
Route::get('announcement/find/{id?}', [AnnouncementController::class, 'find'])->name('announcement.find');
Route::delete('announcement/destroy/{id?}', [AnnouncementController::class, 'destroy'])->name('announcement.destroy');
Route::post('announcement/show/{id?}', [AnnouncementController::class, 'show'])->name('announcement.show');
Route::post('announcement/hide/{id?}', [AnnouncementController::class, 'hide'])->name('announcement.hide');


//contact
Route::get('contact/', [AdminContactController::class, 'index'])->name('contact.index');
Route::post('contact/store', [AdminContactController::class, 'store'])->name('contact.store');
Route::get('contact/list', [AdminContactController::class, 'list'])->name('contact.list');
Route::get('contact/find/{id?}', [AdminContactController::class, 'find'])->name('contact.find');
Route::delete('contact/destroy/{id?}', [AdminContactController::class, 'destroy'])->name('contact.destroy');


//sport equipment request
Route::get('request-sport/', [AdminRequestSport::class, 'index'])->name('request-sport.index');
Route::get('request-sport/store', [AdminRequestSport::class, 'store'])->name('request-sport.store');
Route::get('request-sport/list', [AdminRequestSport::class, 'list'])->name('request-sport.list');
Route::post('request-sport/approave', [AdminRequestSport::class, 'approave'])->name('request-sport.approave');
Route::post('request-sport/decline', [AdminRequestSport::class, 'decline'])->name('request-sport.decline');
Route::post('request-sport/return', [AdminRequestSport::class, 'return'])->name('request-sport.return');
Route::get('request-sport/add', [AdminRequestSport::class, 'add'])->name('request-sport.add');
Route::get('sports/qnty/{id?}', [AdminRequestSport::class, 'qnty'])->name('sports.qnty');
Route::post('sports/store-request/', [AdminRequestSport::class, 'storeRequest'])->name('sports.store-request');


//barangay equipment request
Route::get('request-barangay/', [AdminRequestBrgy::class, 'index'])->name('request-barangay.index');
Route::get('request-barangay/store', [AdminRequestBrgy::class, 'store'])->name('request-barangay.store');
Route::get('request-barangay/list', [AdminRequestBrgy::class, 'list'])->name('request-barangay.list');
Route::post('request-barangay/approave', [AdminRequestBrgy::class, 'approave'])->name('request-barangay.approave');
Route::post('request-barangay/decline', [AdminRequestBrgy::class, 'decline'])->name('request-barangay.decline');
Route::post('request-barangay/return', [AdminRequestBrgy::class, 'return'])->name('request-barangay.return');
Route::get('request-barangay/add', [AdminRequestBrgy::class, 'add'])->name('request-barangay.add');
Route::get('barangay/qnty/{id?}', [AdminRequestBrgy::class, 'qnty'])->name('barangay.qnty');
Route::post('barangay/store-request/', [AdminRequestBrgy::class, 'storeRequest'])->name('barangay.store-request');


//system management
Route::get('system', [SystemController::class, 'index'])->name('system.index');
Route::post('system/edit', [SystemController::class, 'edit'])->name('system.edit');

//barangay indigency
Route::get('barangay-indigency/', [BrgyIndigencyController::class, 'index'])->name('barangay_indigency.index');
Route::get('barangay-indigency/store', [BrgyIndigencyController::class, 'store'])->name('barangay_indigency.store');

resources/views/AdminSystemManagement/index.blade.php
@extends('Layout.app_admin')
@section('title', 'System Management')
@section('css')
<style type="text/css">
.form-control:focus {
box-shadow: none;
border-color: #BA68C8
}
.profile-button {
background: rgb(99, 39, 120);
box-shadow: none;
border: none
}
.profile-button:hover {
background: #682773
}
.profile-button:focus {
background: #682773;
box-shadow: none
}
.profile-button:active {
background: #682773;
box-shadow: none
}
.back:hover {
color: #682773;
cursor: pointer
}
.labels {
font-size: 11px
}
.add-experience:hover {
background: #BA68C8;
color: #fff;
cursor: pointer;
border: solid 1px #BA68C8
}
.container-fluid{
height: 100vh;
}
</style>
@endsection
@section('content')
<div class="container-fluid form-group">
  <div class="row justify-content-center">
    <div class="col-md-5">
      <div class="d-flex flex-column align-items-center text-center p-3 py-5">
        <div>
          <h4>System Name</h4>
        </div>
        <div class="mb-4">
          <form action="{{ route('admin.system.edit') }}" id="system_form" class="needs-validation">
            <input type="hidden" id="system_id" name="system_id" value="{{ $system->id ?? ''}}">
            <input type="text" name="system_name" class="form-control text-center" placeholder="Enter system name here" value="{{ $system->system_name ?? '' }}">
          </div>
          <h4>System Logo</h4>
          @if(!empty($system->logo))
          <img class="rounded-circle img-thumbnail" id="img_shower" src="{{ asset('storage/'.$system->logo) }}" style="width: 260px; height:260px; ">
          @else
          <img class="rounded-circle img-thumbnail" id="img_shower" src="{{ asset('img/default.png') }}" style="width: 260px; height:260px; ">
          @endif
          
          <div class="col-sm-8 mt-2 img_buttons">
            <button type="button" class="btn btn-sm btn-info px-5" onclick="upload_img_btn()">browse photo</button>
          </div>
          <input type="file" class="form-control" name="img" id="img" hidden="" />
        </div>
      </div>
      <div class="col-md-5">
        <div class="p-3 py-5">
          <div class="d-flex justify-content-between align-items-center mb-3">
            <h4 class="text-right">Barangay Captain Info</h4>
          </div>
          <div class="row mt-2">
            <div class="col-md-12 form-group">
              <input type="hidden" name="id" id="id" class="form-control bg-light" value="{{ $user->id ?? '' }}">
              
              <label class="labels">Fullname</label>
              <input type="text" name="full_name" id="full_name" class="form-control bg-light" placeholder="Enter Fullname"
              value="{{ $user->first_name ?? ''}}">
              <div class="invalid-feedback text-left" id="err_full_name"></div>
            </div>
            <div class="col-md-12 form-group">
              <label class="labels">Address</label>
              <input type="text" class="form-control bg-light" placeholder="Enter Address" id="address" name="address" value="{{ $user->address ?? '' }}">
              <div class="invalid-feedback text-left" id="err_address"></div>
            </div>
            <div class="col-md-12 form-group">
              <label class="labels">Gender</label>
              <select class="form-control bg-light" id="gender" name="gender">
                <option disabled="" selected="">Please select gender</option>
                @if(!empty($user->gender))
                <option value="Male" {{ $user->gender == "Male" ? "selected" : '' }}>Male</option>
                <option value="Female" {{ $user->gender == "Female" ? "selected" : '' }}>Female</option>
                @else
                <option value="Male">Male</option>
                <option value="Female">Female</option>
                @endif
                
              </select>
              <div class="invalid-feedback text-left" id="err_gender"></div>
            </div>
            <div class="col-md-12 form-group">
              <label class="labels">Contact Number</label>
              <input type="text" class="form-control bg-light" placeholder="Enter phone number" id="contact" name="contact" value="{{ $user->contact ?? ''}}">
              <div class="invalid-feedback text-left" id="err_contact"></div>
            </div>
            <div class="col-md-12 form-group">
              <label class="labels">Email</label>
              <input type="text" class="form-control bg-light" placeholder="Enter email address" id="email" name="email" value="{{ $user->email_address ?? '' }}">
              <div class="invalid-feedback text-left" id="err_email"></div>
            </div>
            <div class="col-md-12 form-group mt-3">
              <div class="row justify-content-center">
                <div class="col-sm-12">
                  <button type="submit" class="btn col-sm-12 btn-success">
                  <strong>Save</strong>
                  </button>
                </form>
              </div>
            </div>
          </div>
@endsection
@section('script')
<script type="text/javascript">

  $('#system_form').on('submit', function(e){
    e.preventDefault();
    let form = $("#system_form")[0];
    // Create an FormData object 
    var data = new FormData(form);
    let url = $(this).attr('action');
    $.ajax({
          type:"POST",
          url:url,
          data:data,
          enctype: 'multipart/form-data',
          processData: false,  // Important!
          contentType: false,
          dataType:'json',
          beforeSend:function(){
          },
          success:function(response){
            // console.log(response);
           if (response.status == true) {
              Swal.fire({
                  position: 'center',
                  icon: 'success',
                  title: response.message,
                  showConfirmButton: false,
                  timer: 1500,
                })

                setTimeout(function(){
                  location.reload();
                }, 2000);
              
           }else{
            showValidator(response.error,'system_form');
            if (response.message) {
              Swal.fire({
                  position: 'center',
                  icon: 'error',
                  title: response.message,
                  showConfirmButton: false,
                  timer: 4500,
                })
            }
              
            console.log(response);
           }
           
           
          },
          error: function(error){
            console.log(error);
          }
        });

  });

function upload_img_btn(){
  $('#img').trigger('click');
}

</script>
    <script>
      var selDiv = "";
      var storedFiles = [];
      $(document).ready(function () {
        $("#img").on("change", handleFileSelect);
        selDiv = $("#img_shower");
      });

      function handleFileSelect(e) {
        var files = e.target.files;
        var filesArr = Array.prototype.slice.call(files);
        filesArr.forEach(function (f) {
          if (!f.type.match("image.*")) {
            return;
          }
          storedFiles.push(f);

          var reader = new FileReader();
          reader.onload = function (e) {
             $("#img_shower").attr('src', e.target.result);
             $("#img_shower").attr('data-file', f.name);
          };
          reader.readAsDataURL(f);
        });
      }
    </script>
@endsection