routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\AdminProfileController;
use App\Http\Controllers\CedulaRequestController;
use App\Http\Controllers\UserProfileController;
use App\Http\Controllers\SportEquipmentController;
use App\Http\Controllers\BarangayEquipmentController;
use App\Http\Controllers\AdminUserManagementController;
use App\Http\Controllers\AnnouncementController;
use App\Http\Controllers\AdminContactController;
use App\Http\Controllers\UserSportsEquipmentController;
use App\Http\Controllers\UserBrgyEquipmentController;
use App\Http\Controllers\AdminRequestSport;
use App\Http\Controllers\AdminRequestBrgy;
use App\Http\Controllers\CourtRequestController;
use App\Http\Controllers\SystemController;
use App\Http\Controllers\BrgyClearanceController;
use App\Http\Controllers\BrgyIndigencyController;
use App\Http\Controllers\UserBrgyClearanceController;
use App\Http\Controllers\UserBrgyIndigencyController;
use App\Http\Controllers\AdminGymController;
use App\Http\Controllers\ReportsController;
use App\Http\Controllers\VerifyAccountController;
use App\Http\Controllers\AdminVerifyController;


// Login
Route::get('/', [AuthController::class, 'index'])->name('login');
Route::post('/login', [AuthController::class, 'check_login'])->name('auth.check');
Route::get('/logout', [AuthController::class, 'logoutUser'])->name('auth.logout');
Route::get('/registration', [AuthController::class, 'registration'])->name('auth.registration');
Route::post('/registration/add', [AuthController::class, 'registrationAdd'])->name('auth.registration.add');
Route::get('/forget_pass', [AuthController::class, 'forgetPass'])->name('auth.forget_pass');
Route::post('/forget_pass/save', [AuthController::class, 'forgetPassSave'])->name('auth.forget_pass_save');
Route::get('/change/password/{id?}', [AuthController::class, 'changePass'])->name('auth.change_password');
Route::post('/change/password/save/{id?}', [AuthController::class, 'changePassSave'])->name('auth.change_password_save');
Route::post('/reset/password/save/{id?}', [AuthController::class, 'resetPassSave'])->name('auth.reset_password_save');


// admin modules
Route::group(['middleware' => ['auth', 'AuthAdmin']], function(){
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function(){

// admin Dashboard
Route::get('/dashboard', [DashboardController::class, 'index'])->name('index');

//admin Verify
Route::get('admin-verify/', [AdminVerifyController::class, 'index'])->name('verify.index');
Route::get('admin-verify/list', [AdminVerifyController::class, 'list'])->name('verify.list');
Route::get('admin-verify/find/{id?}', [AdminVerifyController::class, 'find'])->name('verify.find');
Route::post('admin-verify/approve/{id?}', [AdminVerifyController::class, 'approve'])->name('verify.approve');
Route::post('admin-verify/disapprove/{id?}', [AdminVerifyController::class, 'disapprove'])->name('verify.disapprove');



//admin profile
Route::get('profile', [AdminProfileController::class, 'index'])->name('profile.index');
Route::post('profile/edit', [AdminProfileController::class, 'edit'])->name('profile.edit');
Route::get('profile/find/{id?}', [AdminProfileController::class, 'find'])->name('profile.find');
Route::get('profile/change-password', [AdminProfileController::class, 'changePassword'])->name('profile.change.password');
Route::post('profile/upload', [AdminProfileController::class, 'upload'])->name('profile.upload');

//AdminUserInformationController
Route::get('UserInformation', [AdminUserInformationController::class, 'index'])->name('UserInformation.index');
Route::get('UserInformation/list', [AdminUserInformationController::class, 'list'])->name('UserInformation.list');

//sports_equipment
Route::get('sports/equipments', [SportEquipmentController::class, 'index'])->name('sports.index');
Route::get('sports/store', [SportEquipmentController::class, 'store'])->name('sports.store');
Route::get('sports/list', [SportEquipmentController::class, 'list'])->name('sports.list');
Route::get('sports/find/{id?}', [SportEquipmentController::class, 'find'])->name('sports.find');
Route::post('sports/destroy/{id?}', [SportEquipmentController::class, 'destroy'])->name('sports.destroy');
Route::get('sports/select', [SportEquipmentController::class, 'select'])->name('sports.select');
Route::get('sports/qnty/{id?}', [SportEquipmentController::class, 'qnty'])->name('sports.qnty');
Route::post('sports/stock-in', [SportEquipmentController::class, 'stockIn'])->name('sports.stockIn');
Route::post('sports/stock-out', [SportEquipmentController::class, 'stockOut'])->name('sports.stockOut');

//barangay_equipment
Route::get('barangay/equipments', [BarangayEquipmentController::class, 'index'])->name('barangay.index');
Route::get('barangay/store', [BarangayEquipmentController::class, 'store'])->name('barangay.store');
Route::get('barangay/list', [BarangayEquipmentController::class, 'list'])->name('barangay.list');
Route::get('barangay/find/{id?}', [BarangayEquipmentController::class, 'find'])->name('barangay.find');
Route::post('barangay/destroy/{id?}', [BarangayEquipmentController::class, 'destroy'])->name('barangay.destroy');
Route::get('barangay/select', [BarangayEquipmentController::class, 'select'])->name('barangay.select');
Route::get('barangay/qnty/{id?}', [BarangayEquipmentController::class, 'qnty'])->name('barangay.qnty');
Route::post('barangay/stock-in', [BarangayEquipmentController::class, 'stockIn'])->name('barangay.stockIn');
Route::post('barangay/stock-out', [BarangayEquipmentController::class, 'stockOut'])->name('barangay.stockOut');

//user_management
Route::get('user-management/', [AdminUserManagementController::class, 'index'])->name('users.index');
Route::get('user-management/store', [AdminUserManagementController::class, 'store'])->name('users.store');
Route::get('user-management/list', [AdminUserManagementController::class, 'list'])->name('users.list');
Route::get('user-management/find/{id?}', [AdminUserManagementController::class, 'find'])->name('users.find');
Route::delete('user-management/destroy/{id?}', [AdminUserManagementController::class, 'destroy'])->name('users.destroy');

//announcement
Route::get('announcement/', [AnnouncementController::class, 'index'])->name('announcement.index');
Route::post('announcement/store', [AnnouncementController::class, 'store'])->name('announcement.store');
Route::get('announcement/list', [AnnouncementController::class, 'list'])->name('announcement.list');
Route::get('announcement/find/{id?}', [AnnouncementController::class, 'find'])->name('announcement.find');
Route::delete('announcement/destroy/{id?}', [AnnouncementController::class, 'destroy'])->name('announcement.destroy');
Route::post('announcement/show/{id?}', [AnnouncementController::class, 'show'])->name('announcement.show');
Route::post('announcement/hide/{id?}', [AnnouncementController::class, 'hide'])->name('announcement.hide');


//contact
Route::get('contact/', [AdminContactController::class, 'index'])->name('contact.index');
Route::post('contact/store', [AdminContactController::class, 'store'])->name('contact.store');
Route::get('contact/list', [AdminContactController::class, 'list'])->name('contact.list');
Route::get('contact/find/{id?}', [AdminContactController::class, 'find'])->name('contact.find');
Route::delete('contact/destroy/{id?}', [AdminContactController::class, 'destroy'])->name('contact.destroy');


//sport equipment request
Route::get('request-sport/', [AdminRequestSport::class, 'index'])->name('request-sport.index');
Route::get('request-sport/store', [AdminRequestSport::class, 'store'])->name('request-sport.store');
Route::get('request-sport/list', [AdminRequestSport::class, 'list'])->name('request-sport.list');
Route::post('request-sport/approave', [AdminRequestSport::class, 'approave'])->name('request-sport.approave');
Route::post('request-sport/decline', [AdminRequestSport::class, 'decline'])->name('request-sport.decline');
Route::post('request-sport/return', [AdminRequestSport::class, 'return'])->name('request-sport.return');
Route::get('request-sport/add', [AdminRequestSport::class, 'add'])->name('request-sport.add');
Route::get('sports/qnty/{id?}', [AdminRequestSport::class, 'qnty'])->name('sports.qnty');
Route::post('sports/store-request/', [AdminRequestSport::class, 'storeRequest'])->name('sports.store-request');


//barangay equipment request
Route::get('request-barangay/', [AdminRequestBrgy::class, 'index'])->name('request-barangay.index');
Route::get('request-barangay/store', [AdminRequestBrgy::class, 'store'])->name('request-barangay.store');
Route::get('request-barangay/list', [AdminRequestBrgy::class, 'list'])->name('request-barangay.list');
Route::post('request-barangay/approave', [AdminRequestBrgy::class, 'approave'])->name('request-barangay.approave');
Route::post('request-barangay/decline', [AdminRequestBrgy::class, 'decline'])->name('request-barangay.decline');
Route::post('request-barangay/return', [AdminRequestBrgy::class, 'return'])->name('request-barangay.return');
Route::get('request-barangay/add', [AdminRequestBrgy::class, 'add'])->name('request-barangay.add');
Route::get('barangay/qnty/{id?}', [AdminRequestBrgy::class, 'qnty'])->name('barangay.qnty');
Route::post('barangay/store-request/', [AdminRequestBrgy::class, 'storeRequest'])->name('barangay.store-request');


//system management
Route::get('system', [SystemController::class, 'index'])->name('system.index');
Route::post('system/edit', [SystemController::class, 'edit'])->name('system.edit');

//barangay indigency
Route::get('barangay-indigency/', [BrgyIndigencyController::class, 'index'])->name('barangay_indigency.index');
Route::get('barangay-indigency/store', [BrgyIndigencyController::class, 'store'])->name('barangay_indigency.store');

resources/views/Admin/index.blade.php
@extends('Layout.app_admin')
@section('title', 'Admin Dashboard')
@section('content')
<!-- Content Wrapper. Contains page content -->
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0">Dashboard</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Dashboard</li>
          </ol>
          </div><!-- /.col -->
          </div><!-- /.row -->
          </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->
        <!-- Main content -->
        <section class="content">
          <div class="container-fluid">
            <!-- Small boxes (Stat box) -->
            <div class="row">

              <div class="col-lg-4 col-12">
                <!-- small box -->
                <div class="small-box bg-info">
                  <div class="inner">
                    <h3>{{ BarangayEquipmentRent() }}<span class="badge badge-sm badge-danger text-md float-sm-right">New</span></h3>
                    <p>Barangay Equipment Request  &nbsp;(Today)</p>
                  </div>
                  <div class="icon">
                    <i class="fas fa-chair"></i>
                  </div>
                  <a href="{{ route('admin.request-barangay.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
              </div>
              <!-- ./col -->
              <div class="col-lg-4 col-12">
                <!-- small box -->
                <div class="small-box bg-danger">
                  <div class="inner">
                    <h3>{{ SportEquipmentRent() }} <span class="badge badge-sm badge-danger text-md float-sm-right">New</span></h3>
                    <p>Sports Equipment Request  &nbsp;(Today)</p>
                  </div>
                  <div class="icon">
                    <i class="fas fa-baseball-ball"></i>
                  </div>
                  <a href="{{ route('admin.request-sport.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
              </div>
              


              <div class="col-lg-4 col-12">
                <!-- small box -->
                <div class="small-box bg-warning">
                  <div class="inner">
                    <h3>{{ BarangayIndigency() }} <span class="badge badge-sm badge-danger text-md float-sm-right">New</span></h3>
                    <p>Barangay Indigency Request &nbsp;(Today)</p>
                  </div>
                  <div class="icon">
                    <i class="fas fa-baseball-ball"></i>
                  </div>
                  <a href="{{ route('admin.barangay_indigency.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
              </div>

              <div class="col-lg-3 col-12">
                <!-- small box -->
                <div class="small-box bg-success">
                  <div class="inner">
                    <h3>{{ BarangayClearance() }} <span class="badge badge-sm badge-danger text-md float-sm-right">New</span></h3>
                    <p>Barangay Clearance Request &nbsp;(Today)</p>
                  </div>
                  <div class="icon">
                    <i class="fas fa-baseball-ball"></i>
                  </div>
                  <a href="{{ route('admin.barangay_clearance.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
              </div>
              <!-- ./col -->
              <div class="col-lg-3 col-12">
                <!-- small box -->
                <div class="small-box bg-warning">
                  <div class="inner">
                    <h3>{{ totalAnnouncement() }}</h3>
                    <p>Announcement</p>
                  </div>
                  <div class="icon">
                    <i class="fas fa-file-alt"></i>
                  </div>
                  <a href="{{ route('admin.announcement.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
              </div>
              <!-- ./col -->
              <div class="col-lg-3 col-12">
                <!-- small box -->
                <div class="small-box bg-info">
                  <div class="inner">
                    <h3>{{ totalUser() }}</h3>
                    <p>Total users</p>
                  </div>
                  <div class="icon">
                    <i class="fas fa-baseball-ball"></i>
                  </div>
                  <a href="{{ route('admin.users.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
              </div>
              <div class="col-lg-3 col-12">
                <!-- small box -->
                <div class="small-box" style="background-color: tomato">
                  <div class="inner">
                    <h3>{{ Gymcount() }}<span class="badge badge-sm badge-danger text-md float-sm-right">New</span></h3>
                    <p>Gymnasium Scheduling Request &nbsp;(Today)</p>
                  </div>
                  <div class="icon">
                    <i class="fas fa-baseball-ball"></i>
                  </div>
                  <a href="{{ route('admin.Gym_scheduling.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
              </div>
              <!-- ./col -->
            </div>
@endsection
@section('script')
<script type="text/javascript">

</script>
@endsection