routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\AdminProfileController;
use App\Http\Controllers\CedulaRequestController;
use App\Http\Controllers\UserProfileController;
use App\Http\Controllers\SportEquipmentController;
use App\Http\Controllers\BarangayEquipmentController;
use App\Http\Controllers\AdminUserManagementController;
use App\Http\Controllers\AnnouncementController;
use App\Http\Controllers\AdminContactController;
use App\Http\Controllers\UserSportsEquipmentController;
use App\Http\Controllers\UserBrgyEquipmentController;
use App\Http\Controllers\AdminRequestSport;
use App\Http\Controllers\AdminRequestBrgy;
use App\Http\Controllers\CourtRequestController;
use App\Http\Controllers\SystemController;
use App\Http\Controllers\BrgyClearanceController;
use App\Http\Controllers\BrgyIndigencyController;
use App\Http\Controllers\UserBrgyClearanceController;
use App\Http\Controllers\UserBrgyIndigencyController;
use App\Http\Controllers\AdminGymController;
use App\Http\Controllers\ReportsController;
use App\Http\Controllers\VerifyAccountController;
use App\Http\Controllers\AdminVerifyController;


// Login
Route::get('/', [AuthController::class, 'index'])->name('login');
Route::post('/login', [AuthController::class, 'check_login'])->name('auth.check');
Route::get('/logout', [AuthController::class, 'logoutUser'])->name('auth.logout');
Route::get('/registration', [AuthController::class, 'registration'])->name('auth.registration');
Route::post('/registration/add', [AuthController::class, 'registrationAdd'])->name('auth.registration.add');
Route::get('/forget_pass', [AuthController::class, 'forgetPass'])->name('auth.forget_pass');
Route::post('/forget_pass/save', [AuthController::class, 'forgetPassSave'])->name('auth.forget_pass_save');
Route::get('/change/password/{id?}', [AuthController::class, 'changePass'])->name('auth.change_password');
Route::post('/change/password/save/{id?}', [AuthController::class, 'changePassSave'])->name('auth.change_password_save');
Route::post('/reset/password/save/{id?}', [AuthController::class, 'resetPassSave'])->name('auth.reset_password_save');


// admin modules
Route::group(['middleware' => ['auth', 'AuthAdmin']], function(){
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function(){

// admin Dashboard
Route::get('/dashboard', [DashboardController::class, 'index'])->name('index');

//admin Verify
Route::get('admin-verify/', [AdminVerifyController::class, 'index'])->name('verify.index');
Route::get('admin-verify/list', [AdminVerifyController::class, 'list'])->name('verify.list');
Route::get('admin-verify/find/{id?}', [AdminVerifyController::class, 'find'])->name('verify.find');
Route::post('admin-verify/approve/{id?}', [AdminVerifyController::class, 'approve'])->name('verify.approve');
Route::post('admin-verify/disapprove/{id?}', [AdminVerifyController::class, 'disapprove'])->name('verify.disapprove');



//admin profile
Route::get('profile', [AdminProfileController::class, 'index'])->name('profile.index');
Route::post('profile/edit', [AdminProfileController::class, 'edit'])->name('profile.edit');
Route::get('profile/find/{id?}', [AdminProfileController::class, 'find'])->name('profile.find');
Route::get('profile/change-password', [AdminProfileController::class, 'changePassword'])->name('profile.change.password');
Route::post('profile/upload', [AdminProfileController::class, 'upload'])->name('profile.upload');

//AdminUserInformationController
Route::get('UserInformation', [AdminUserInformationController::class, 'index'])->name('UserInformation.index');
Route::get('UserInformation/list', [AdminUserInformationController::class, 'list'])->name('UserInformation.list');

//sports_equipment
Route::get('sports/equipments', [SportEquipmentController::class, 'index'])->name('sports.index');
Route::get('sports/store', [SportEquipmentController::class, 'store'])->name('sports.store');
Route::get('sports/list', [SportEquipmentController::class, 'list'])->name('sports.list');
Route::get('sports/find/{id?}', [SportEquipmentController::class, 'find'])->name('sports.find');
Route::post('sports/destroy/{id?}', [SportEquipmentController::class, 'destroy'])->name('sports.destroy');
Route::get('sports/select', [SportEquipmentController::class, 'select'])->name('sports.select');
Route::get('sports/qnty/{id?}', [SportEquipmentController::class, 'qnty'])->name('sports.qnty');
Route::post('sports/stock-in', [SportEquipmentController::class, 'stockIn'])->name('sports.stockIn');
Route::post('sports/stock-out', [SportEquipmentController::class, 'stockOut'])->name('sports.stockOut');

//barangay_equipment
Route::get('barangay/equipments', [BarangayEquipmentController::class, 'index'])->name('barangay.index');
Route::get('barangay/store', [BarangayEquipmentController::class, 'store'])->name('barangay.store');
Route::get('barangay/list', [BarangayEquipmentController::class, 'list'])->name('barangay.list');
Route::get('barangay/find/{id?}', [BarangayEquipmentController::class, 'find'])->name('barangay.find');
Route::post('barangay/destroy/{id?}', [BarangayEquipmentController::class, 'destroy'])->name('barangay.destroy');
Route::get('barangay/select', [BarangayEquipmentController::class, 'select'])->name('barangay.select');
Route::get('barangay/qnty/{id?}', [BarangayEquipmentController::class, 'qnty'])->name('barangay.qnty');
Route::post('barangay/stock-in', [BarangayEquipmentController::class, 'stockIn'])->name('barangay.stockIn');
Route::post('barangay/stock-out', [BarangayEquipmentController::class, 'stockOut'])->name('barangay.stockOut');

//user_management
Route::get('user-management/', [AdminUserManagementController::class, 'index'])->name('users.index');
Route::get('user-management/store', [AdminUserManagementController::class, 'store'])->name('users.store');
Route::get('user-management/list', [AdminUserManagementController::class, 'list'])->name('users.list');
Route::get('user-management/find/{id?}', [AdminUserManagementController::class, 'find'])->name('users.find');
Route::delete('user-management/destroy/{id?}', [AdminUserManagementController::class, 'destroy'])->name('users.destroy');

//announcement
Route::get('announcement/', [AnnouncementController::class, 'index'])->name('announcement.index');
Route::post('announcement/store', [AnnouncementController::class, 'store'])->name('announcement.store');
Route::get('announcement/list', [AnnouncementController::class, 'list'])->name('announcement.list');
Route::get('announcement/find/{id?}', [AnnouncementController::class, 'find'])->name('announcement.find');
Route::delete('announcement/destroy/{id?}', [AnnouncementController::class, 'destroy'])->name('announcement.destroy');
Route::post('announcement/show/{id?}', [AnnouncementController::class, 'show'])->name('announcement.show');
Route::post('announcement/hide/{id?}', [AnnouncementController::class, 'hide'])->name('announcement.hide');


//contact
Route::get('contact/', [AdminContactController::class, 'index'])->name('contact.index');
Route::post('contact/store', [AdminContactController::class, 'store'])->name('contact.store');
Route::get('contact/list', [AdminContactController::class, 'list'])->name('contact.list');
Route::get('contact/find/{id?}', [AdminContactController::class, 'find'])->name('contact.find');
Route::delete('contact/destroy/{id?}', [AdminContactController::class, 'destroy'])->name('contact.destroy');


//sport equipment request
Route::get('request-sport/', [AdminRequestSport::class, 'index'])->name('request-sport.index');
Route::get('request-sport/store', [AdminRequestSport::class, 'store'])->name('request-sport.store');
Route::get('request-sport/list', [AdminRequestSport::class, 'list'])->name('request-sport.list');
Route::post('request-sport/approave', [AdminRequestSport::class, 'approave'])->name('request-sport.approave');
Route::post('request-sport/decline', [AdminRequestSport::class, 'decline'])->name('request-sport.decline');
Route::post('request-sport/return', [AdminRequestSport::class, 'return'])->name('request-sport.return');
Route::get('request-sport/add', [AdminRequestSport::class, 'add'])->name('request-sport.add');
Route::get('sports/qnty/{id?}', [AdminRequestSport::class, 'qnty'])->name('sports.qnty');
Route::post('sports/store-request/', [AdminRequestSport::class, 'storeRequest'])->name('sports.store-request');


//barangay equipment request
Route::get('request-barangay/', [AdminRequestBrgy::class, 'index'])->name('request-barangay.index');
Route::get('request-barangay/store', [AdminRequestBrgy::class, 'store'])->name('request-barangay.store');
Route::get('request-barangay/list', [AdminRequestBrgy::class, 'list'])->name('request-barangay.list');
Route::post('request-barangay/approave', [AdminRequestBrgy::class, 'approave'])->name('request-barangay.approave');
Route::post('request-barangay/decline', [AdminRequestBrgy::class, 'decline'])->name('request-barangay.decline');
Route::post('request-barangay/return', [AdminRequestBrgy::class, 'return'])->name('request-barangay.return');
Route::get('request-barangay/add', [AdminRequestBrgy::class, 'add'])->name('request-barangay.add');
Route::get('barangay/qnty/{id?}', [AdminRequestBrgy::class, 'qnty'])->name('barangay.qnty');
Route::post('barangay/store-request/', [AdminRequestBrgy::class, 'storeRequest'])->name('barangay.store-request');


//system management
Route::get('system', [SystemController::class, 'index'])->name('system.index');
Route::post('system/edit', [SystemController::class, 'edit'])->name('system.edit');

//barangay indigency
Route::get('barangay-indigency/', [BrgyIndigencyController::class, 'index'])->name('barangay_indigency.index');
Route::get('barangay-indigency/store', [BrgyIndigencyController::class, 'store'])->name('barangay_indigency.store');

app/Http/Controllers/AdminVerifyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;


class AdminVerifyController extends Controller
{
    public function index(){
        return view('AdminVerify.index');
    }

    public function list(Request $request){
        if (!empty($request->get('status_filter'))) {
        
        $User = User::whereNull('deleted_at')->where('type', 3)->where('status','!=', 1)->where('status', $request->get('status_filter'))->orderBy('status', 'asc')->orderBy('id', 'desc')->get();
        }else{
        $User = User::whereNull('deleted_at')->where('type', 3)->where('status','!=', 1)->orderBy('id', 'desc')->get();
        }
        return response()->json(['status' => true, 'data' => $User]);
    }

    public function find(Request $request, $id){
        $img = User::find($id);
        return response()->json(['status' => true, 'data' => $img]);
    }

    public function approve(Request $request, $id){
        $img = User::find($id);
        $img->status = 3;
        $img->save();
        return response()->json(['status' => true]);
    }

    public function disapprove(Request $request, $id){
        $img = User::find($id);
        $img->status = 4;
        $img->save();
        return response()->json(['status' => true]);
    }
}

resources/views/AdminVerify/index.blade.php
@extends('Layout.app_admin')
@section('title', 'Verify users')
@section('css')
<style type="text/css">
</style>
@endsection
@section('content')
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0">Verify users</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{ route('admin.index') }}">Home</a></li>
            <li class="breadcrumb-item active">Verify users</li>
          </ol>
          </div><!-- /.col -->
          </div><!-- /.row -->
          </div><!-- /.container-fluid -->
        </div>
	<form class="needs-validation" id="all_data_form" action="{{ route('admin.users.store') }}" novalidate>
		<div class="container-fluid">
			<div class="card">
				<div class="card-header" onclick="$('#minimize_filter').click()" >
					<h5 class="card-title">Record Filter</h5>
					<div class="card-tools">
						<button type="button" class="btn btn-tool" data-card-widget="collapse">
						<i class="fas fa-minus"></i>
						</button>
					</div>
				</div>
				
				<div class="card-body">
					<div class="row">
						<div class="mb-2 col-md-3">
							<label>Status Filter</label>
							<select class="form-control" id="status_filter" name="status_filter">
								<option value="">Select Status</option>
								<option value="2">Pending</option>
								<option value="3">Approved</option>
								<option value="4">Disapproved</option>
							</select>
						</div>

					
					</div>
					
				</div>
				<div class="card-footer text-right">
					<!-- <button type="button" class="btn btn-secondary" data-card-widget="collapse" id="minimize_filter">
					<i class="fa fa-minus"></i> Minimize Filter
					</button> -->
					<button type="button" id="refresh-filter" class="btn btn-success btn-md"><i class="fa fa-sync-alt"></i> Refresh Filter</button>
					<button type="button" class="btn btn-info btn-md" onclick="submit_filter()"><i class="fa fa-search"></i> Run Filter</button>
				</div>
				
			</div>
			<div class="card">
				<div class="card-body">
					<div class="table-responsive">
					<table class="table table-bordered table-hove" id="tbl_user_accounts" style="width: 100%;"></table>
				</div>
			</div>
		</div>
	</div>
	<div class="modal fade" role="dialog" id="modal_add_edit">
		<div class="modal-dialog modal-lg">
			<div class="modal-content">
				<div class="modal-header">
					<div class="modal-title h4">
						Add User Account
					</div>
					<button class="close" data-dismiss="modal">&times;</button>
				</div>
				<div class="modal-body">
					<div class="row">
						<div class="col-sm-4">
							<input type="hidden" name="id" id="id">
							<label class="required">Firstname</label>
							<input type="text" name="first_name" id="first_name" placeholder="Enter firstname here" class="mb-2 form-control" autocomplete="off">
							<div class="invalid-feedback text-left" id="err_first_name"></div>
						</div>
						<div class="col-sm-4">
							<label>Middlename</label>
							<input type="text" name="middle_name" id="middle_name" placeholder="Enter middlename here" class="mb-2 form-control" autocomplete="off">
							<div class="invalid-feedback text-left" id="err_middle_name"></div>
						</div>
						<div class="col-sm-4">
							<label class="required">Lastname</label>
							<input type="text" name="last_name" id="last_name" placeholder="Enter lastname here" class="mb-2 form-control" autocomplete="off">
							<div class="invalid-feedback text-left" id="err_last_name"></div>
						</div>
						<div class="col-sm-12">
							<label class="required">Date of Birth</label>
							<input type="date" name="bday" id="bday" class="mb-2 form-control" autocomplete="off">
							<div class="invalid-feedback text-left" id="err_bday"></div>
						</div>
						<div class="col-sm-6">
							<label class="required">Gender</label>
							<select name="gender" id="gender" class="form-control" autocomplete="off">
								<option selected="" disabled="">Please select gender</option>
								<option value="Male">Male</option>
								<option value="Female">Female</option>
							</select>
							<div class="invalid-feedback text-left" id="err_gender"></div>
						</div>
						<div class="col-sm-6">
							<label class="required">Contact</label>
							<input type="text" name="contact" id="contact" placeholder="Enter contact here" class="mb-2 form-control" autocomplete="off">
							<div class="invalid-feedback text-left" id="err_contact"></div>
						</div>
						<div class="col-sm-12">
							<label class="required">Address</label>
							<textarea class="form-control mb-2" rows="3" id="address" name="address" placeholder="Enter address here"></textarea>
							<div class="invalid-feedback text-left" id="err_address"></div>
						</div>
						<div id="hide_on_edit" class="col-sm-12">
							<div class="col-sm-12">
								<label class="required">Email</label>
								<input type="text" name="email_address" id="email_address" class="form-control mb-2" placeholder="Enter email here">
								<div class="invalid-feedback text-left" id="err_email_address"></div>
							</div>
							<div class="col-sm-12">
								<label class="required">Password</label>
								<input type="password" name="password" id="password" class="form-control mb-2" placeholder="Enter password here">
								<div class="invalid-feedback text-left" id="err_password"></div>
							</div>
							<div class="col-sm-12">
								<label class="required">Confirm Password</label>
								<input type="password" name="confirm_password" id="confirm_password" class="form-control" placeholder="Verify password here">
								<div class="invalid-feedback text-left" id="err_confirm_password"></div>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-danger px-5" data-dismiss="modal">Cancel</button>
					<button type="submit" class="btn btn-success px-5" id="btn_submit">Submit</button>
				</div>
			</div>
		</div>
	</div>
</form>
</div>

 <div class="modal fade" role="dialog" id="view_img_modal">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <div class="modal-title h4">
            
            </div>
            <button class="close" data-dismiss="modal">&times;</button>
          </div>
          <div class="modal-body">
          	<div class="text-center">
            <img src="" alt="" class="img-fluid" id="view_img_shower">
            </div>
          </div>
          <div class="modal-footer">
            <button class="btn btn-danger" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>


@endsection


@section('script')
<script type="text/javascript">


	$('#refresh-filter').on('click', function(){
		$('#filter').val('');
		submit_filter();
	});

	function submit_filter(){
		show_user_accounts();
		$('#minimize_filter').trigger('click');
	}


	show_user_accounts();
	var tbl_user_accounts;
	function show_user_accounts(){
		if (tbl_user_accounts) {
			tbl_user_accounts.destroy();
		}
		tbl_user_accounts = $('#tbl_user_accounts').DataTable({
		pageLength: 10,
		responsive: true,
		deferRender: true,
		aaSorting: [],
		language: {
		"emptyTable": "No data available"
	},
	ajax: {
        url: "{{ route('admin.verify.list') }}",
        data: {status_filter : $('#status_filter').val()},
    },
		columns: [{
		className: '',
		"data": "id",
		"title": "Verification image",
		"orderable": false,
		"width": 150,
    "render": function(data, type, row, meta){
       return newdata = '<button type="button" class="btn btn-info btn-sm col-sm-11" onclick="view_img('+data+')" >View</button>'
    }
	},{
		className: '',
		"data": "id",
		"title": "Fullname",
		"orderable": false,
		"render": function(data, type, row, meta){
		 return newdata = row.first_name+' '+row.last_name
		}
	},{
		className: '',
		"data": "contact",
		"title": "Contact #",
		"orderable": false,
	},{
		className: '',
		"data": "email_address",
		"title": "Email",
		"orderable": false,
	},{
		className: 'text-center',
		"data": "status",
		"title": "Request Status",
		"render": function(data, type, row, meta){
			if (data == 3) {
				newdata = '<td><span class="badge p-2 badge-sm badge-success">Approved</span></td>'
			}else if(data == 2){
				newdata = '<td><span class="badge p-2 badge-sm badge-warning">Pending</span></td>'
			}else{
				newdata = '<td><span class="badge p-2 badge-sm badge-danger">Disapproved</span></td>'
			}
		 return newdata
		}
	},{
		className: 'text-center',
		"data": "id",
		"title": "Options",
		"orderable": false,
		"render": function(data, type, row, meta){
      newdata = '<button type="button" class="btn btn-sm btn-info" onclick="approve('+data+')"><i class="fas fa-thumbs-up"></i> Approve</button>\
				 <button type="button" class="btn btn-sm btn-danger" onclick="disapprove('+data+')"><i class="fas fa-thumbs-down"></i> Disapprove</button>'
		return newdata;
    }
	}
	]
	});
	}

	function view_img(id){
		$.ajax({
            type:"get",
            url:"{{ route('admin.verify.find') }}"+'/'+id,
            data:{},
            dataType:'json',
            beforeSend:function(){
            },
            success:function(response){
             if (response.status == true) {               
                $('#view_img_modal').modal('show');
                
                $("#view_img_shower").attr("src", "http://localhost/malvar-system/public/storage/"+response.data.proof_img+"")
                $('.modal-title').html('Verification Image: '+response.data.first_name+' '+response.data.last_name)
             }else{
              console.log(response);
             }
            },
            error: function(error){
              console.log(error);
            }
          }); 
				}

		function approve(id){
		Swal.fire({
			  title: 'Are you sure?',
			  text: "This request will be approve!",
			  icon: 'warning',
			  showCancelButton: true,
			  confirmButtonColor: '#3085d6',
			  cancelButtonColor: '#d33',
			  confirmButtonText: 'Yes, approve it!'
			}).then((result) => {
			  if (result.isConfirmed) {
			  	$.ajax({
		    type:"post",
		    url:"{{ route('admin.verify.approve') }}"+"/"+id,
		    data:{},
		    dataType:'json',
		    beforeSend:function(){
		    },
		    success:function(response){
		      // console.log(response);
		     if (response.status == true) {
		     	show_user_accounts();
		     	Swal.fire(
			      'Success!',
			      'Account Verified Successfully',
			      'success'
			    )
		       
		     }else{
		     	Swal.fire({
		                position: 'center',
		                icon: 'error',
		                title: response.message,
		                showConfirmButton: false,
		                timer: 4500
		              })
		      console.log(response);
		     }
		    },
		    error: function(error){
		      console.log(error);
		    }
		  });

			    
			  }
			})
	}

	function disapprove(id){
		Swal.fire({
			  title: 'Are you sure?',
			  text: "This request will be disapprove!",
			  icon: 'warning',
			  showCancelButton: true,
			  confirmButtonColor: '#3085d6',
			  cancelButtonColor: '#d33',
			  confirmButtonText: 'Yes, disapprove it!'
			}).then((result) => {
			  if (result.isConfirmed) {
			  	$.ajax({
		    type:"post",
		    url:"{{ route('admin.verify.disapprove') }}"+"/"+id,
		    data:{},
		    dataType:'json',
		    beforeSend:function(){
		    },
		    success:function(response){
		      // console.log(response);
		     if (response.status == true) {
		     	show_user_accounts();
		     	Swal.fire(
			      'Success!',
			      'Account Verification Declined!',
			      'success'
			    )
		       
		     }else{
		     	Swal.fire({
		                position: 'center',
		                icon: 'error',
		                title: response.message,
		                showConfirmButton: false,
		                timer: 4500
		              })
		      console.log(response);
		     }
		    },
		    error: function(error){
		      console.log(error);
		    }
		  });

			    
			  }
			})
	}

	
</script>
@endsection